### ISSUE TITLE
Examples dir should contain .rs files

### ISSUE THREAD

**Issue by MagaTailor** [zack-bitcoin/forth-in-rust#2]
I wondered why `cargo run --example` didn't want to autocomplete...

A means to test the `vm` with no `erlang` installed would be interesting. (benchmarks?)

**Comment by zack-bitcoin** [comment]
erlang is just a compiler. I could leave the compiled versions of all the files in the folder, so you can run them without having erlang installed.

**Comment by MagaTailor** [comment]
Indeed, that would be the Rust-only way to do it. The old tests, using the erlang compiler, could maybe run via a script?

**Comment by zack-bitcoin** [comment]
im trying to figure out how to use command line arguments with rust.
It is hard coded to only run that one file.
I need it to be able to run any of the files.

**Comment by MagaTailor** [comment]
Not sure if that's what you meant:

http://doc.crates.io/manifest.html#examples

**Comment by zack-bitcoin** [comment]
no, I don't want to import rust code.
I need a command line input saying where the compiled forth code is.
Then I need the rust code to read the contents of that file, and run it.

I figured out how to give command line inputs, now im trying to figure out how to cast my command line input into a type that File::open can accept. &str

**Comment by zack-bitcoin** [comment]
ok, I got it working. the compiled code is now included.

**Comment by zack-bitcoin** [comment]
thanks for the suggestion.

**Comment by MagaTailor** [comment]
Yup, it works for me:

``` shell
for i in examples/*.bytes ; do target/release/vm $i ; done
```

```
30
17711
10946
233168
2048
4
```
